apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-reelatable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-reelatable
  template:
    metadata:
      labels:
        app: flask-reelatable
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: flask-reelatable
        image: gcr.io/reelatable-420506/docker-flask-reelatable:202405010012
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "100m"
            memory: "2Gi"
          requests:
            cpu: "50m"
            memory: "1Gi"
