apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-reelatable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-reelatable
  template:
    metadata:
      labels:
        app: flask-reelatable
    spec:
      containers:
      - name: flask-reelatable
        image: gcr.io/reelatable/docker-flask-reelatable:latest
        ports:
        - containerPort: 5000